/**
 * 
 * @author JGreeny
 *
 * @problem Project Euler Problem 2:
 * 			Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * 			By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 			By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * 			find the sum of the even-valued terms.
 *			
 * @solution Generate Fibonacci term.
 * 			 While the term is less than 4 million:
 * 				If term is a multiple of 2, add to total.
 * 				Otherwise, generate next term.
 */

public class Problem2 {
	
	public static void main(String[] args) {
		int max = 4000000,
			t1 = 1, 
			t2 = 2,
			temp = 0,
			total = 0;
		
		while (t2 < max) {
			if (t2 % 2 == 0)
				total += t2;
			
			temp = t1;
			t1 = t2;
			t2 = temp + t1;
		}
		
		System.out.println(total);
	}
}
